name: Generate Digimons JSON

on:
  push:
    paths:
      - 'data/digi_illustration/**/script.json'
      - 'scripts/generate_digimons.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run generate_digimons.py
        run: |
          python scripts/generate_digimons.py

      - name: Commit generated digimons.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/digi_illustration/digimons.json
          git commit -m "🔄 auto-update digimons.json" || echo "No changes to commit"

      - name: Pull and push
        run: |
          git pull --rebase origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
